export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

// export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const PRODUCTBYID_REQUEST = 'PRODUCTBYID_REQUEST';
export const PRODUCTBYID_SUCCESS = 'PRODUCTBYID_SUCCESS';
export const PRODUCTBYID_FAIL = 'PRODUCTBYID_FAIL';
